### ISSUE TITLE
"Grepping seq ids" step fails – Too many open files

### ISSUE THREAD

**Issue by seanmcallister** [mooreryan/lsa_for_genomes#7]
After the kmeans steps, my run fails on the "Grepping seq ids" step.

Error:

```
I, [2017-10-16T18:24:46.780928 #10186]  INFO -- : Grepping seq ids
/home/mcallis/software/lsa_for_genomes/lsa.rb:1182:in `initialize': Too many open files @ rb_sysopen - 04_test/metadata_groups/original/top_terms_by_doc/Genome2/seqs/Genome2_term_doc_dist_cluster_21.fa (Errno::EMFILE)
	from /home/mcallis/software/lsa_for_genomes/lsa.rb:1182:in `open'
	from /home/mcallis/software/lsa_for_genomes/lsa.rb:1182:in `block (3 levels) in <main>'
	from /home/mcallis/software/lsa_for_genomes/lsa.rb:1169:in `each'
	from /home/mcallis/software/lsa_for_genomes/lsa.rb:1169:in `block (2 levels) in <main>'
	from /home/mcallis/.rvm/gems/ruby-2.4.1/gems/parse_fasta-2.2.0/lib/parse_fasta/seq_file.rb:120:in `parse_fasta_line'
	from /home/mcallis/.rvm/gems/ruby-2.4.1/gems/parse_fasta-2.2.0/lib/parse_fasta/seq_file.rb:165:in `block in parse_fasta_lines'
	from /home/mcallis/.rvm/gems/ruby-2.4.1/gems/parse_fasta-2.2.0/lib/parse_fasta/seq_file.rb:164:in `each_line'
	from /home/mcallis/.rvm/gems/ruby-2.4.1/gems/parse_fasta-2.2.0/lib/parse_fasta/seq_file.rb:164:in `parse_fasta_lines'
	from /home/mcallis/.rvm/gems/ruby-2.4.1/gems/parse_fasta-2.2.0/lib/parse_fasta/seq_file.rb:88:in `block in each_record_non_gzipped'
	from /home/mcallis/.rvm/gems/ruby-2.4.1/gems/parse_fasta-2.2.0/lib/parse_fasta/seq_file.rb:87:in `open'
	from /home/mcallis/.rvm/gems/ruby-2.4.1/gems/parse_fasta-2.2.0/lib/parse_fasta/seq_file.rb:87:in `each_record_non_gzipped'
	from /home/mcallis/.rvm/gems/ruby-2.4.1/gems/parse_fasta-2.2.0/lib/parse_fasta/seq_file.rb:79:in `each_record'
	from /home/mcallis/software/lsa_for_genomes/lsa.rb:1158:in `block in <main>'
	from /home/mcallis/software/lsa_for_genomes/lsa.rb:617:in `each'
	from /home/mcallis/software/lsa_for_genomes/lsa.rb:617:in `each_with_index'
	from /home/mcallis/software/lsa_for_genomes/lsa.rb:617:in `<main>'

```

This step works fine with the three genomes in the test dataset, but quickly becomes intractable for datasets with many genomes (here 40+).

Can we have the option to deactivate this step?

Thanks.

**Comment by mooreryan** [comment]
So I'm pretty sure this is because on the complex data sets, you will get nearly as many clusters per genome as documents and the program will open a file for all those clusters at once. We should fix this, but for now, that step is disabled by default with the option to turn it on with the `--grep-seqs` flag as of commit a48802befc5b94bcda8231957eb2f29fde783a33.

**Comment by seanmcallister** [comment]
Can we add a control to not have the grepping on the original genome documents, but turn it on for the metadata genome groupings? The metagenome groups will probably number less than the max open documents on most computers.

**Comment by seanmcallister** [comment]
Ryan fixed by making the grep step only function (when turned on) if the number of documents is less than 20. This means that the number of metadata groups have to be less than 20 to get the grepped seqs (and headers) back.

**Comment by mooreryan** [comment]
@seanmcallister Did this fix work for you?

**Comment by seanmcallister** [comment]
Yes
